### ISSUE TITLE
reis merhaba bişey rica edeceğim

### ISSUE THREAD

**Issue by babalartahliye** [smtttlck/kutuphane-otomasyonu#1]
.

**Comment by smtttlck** [comment]
Kullanabilirsiniz. Kolay gelsin.

**Comment by babalartahliye** [comment]
> Kullanabilirsiniz. Kolay gelsin.

peki bişey daha rica edebilirmiyim hocam

**Comment by babalartahliye** [comment]
birşey daha rica edebilirmiym

**Comment by smtttlck** [comment]
Buyur

**Comment by babalartahliye** [comment]
öncelikle kullanmama izin verdiğin için teşekkür ederim abi hoca tasarımları biyerden alıp almadığımızı kontrol edecek de haziranın 2. haftasına kadar projeyi gizleme şansın bulunuyormu rica etsem

**Comment by smtttlck** [comment]
Üzgünüm. Aktif iş başvurularım olduğu için bu konuda sana yardımcı olamayacağım.

**Comment by babalartahliye** [comment]
peki css kısmını nasıl değiştirebilirim yardımcı olma şansınız varmı

**Comment by smtttlck** [comment]
Değişiklikler yapmana yardımcı olmaya çalışırım. Projeni hazırladığında e-mail üzerinden iletişime geçebilirsin benimle.
